//! SeaORM Entity. Generated by sea-orm-codegen 0.2.6

pub use super::post_has_tags::Entity as PostHasTags;
pub use super::posts::Entity as Posts;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
